### ISSUE TITLE
Shit code

### ISSUE THREAD

**Issue by ui0ppk** [Savefade/LegacyIGN#1]
Fix now retard

**Comment by Savefade** [comment]
Hi, can you please describe the issues that you are experiencing? I would do my best to fix them!

**Comment by ui0ppk** [comment]
ChatGPT you mean?

**Comment by Savefade** [comment]
If you have any issues like bugs, gliches or unexpected behaviour feel free to tell me. ChatGPT was barely used.

**Comment by ui0ppk** [comment]
![image](https://github.com/Savefade/LegacyIGN/assets/113091876/84cffbe6-3a54-4684-8b54-7b71569fbbd6)
bullshit

**Comment by Savefade** [comment]
That is an old upload script from march. I have plans to remake it as this one is buggy.

**Comment by ui0ppk** [comment]
Fix shit code then

**Comment by Savefade** [comment]
I will, please instead of being mean tell me whats wrong. Thank you and have a nice day!

**Comment by ui0ppk** [comment]
Shit code not fixed

**Comment by Savefade** [comment]
Hello, i am going to drop a big update and there it the function you are talking about would be replaced.

**Comment by ui0ppk** [comment]
Fix shit code
