### ISSUE TITLE
Fix some issues.

### ISSUE THREAD

**Issue by ghost** [Savefade/LegacyIGN#2]
1. Stop using ChatGPT (Seriously)
2. Use MySQL AUTO_INCREMENT (So you don't have to get the max userid each time and add a 1 to it)
3. Figure out a better token system (Maybe not use PHP Sessions)
4. Use something like PDO instead of Mysqli
5. Use die() instead of echoing something and then doing exit;
6. Credit where you got the API Responses from

**Comment by Savefade** [comment]
Thank you so much for the suggestions. Sadly I can’t use 3 as when you close the app it logs you out (you would know this if you read readme) and I don’t use any type of sessioning. 6 Okay this goes to my good boi i.instagram.com. Yes i took the responses from the ios 6 instagram back in febuary. Do you think i should make them public?

**Comment by ghost** [comment]
You should put in the README where you took them from.

**Comment by ghost** [comment]
Either way try to find how instagram used to save sessions and try to replicate that. It might work.

**Comment by Savefade** [comment]
Sadly I don’t know how for versions 6.0 below, but i do know how to add that for version 6 up. I do know that versions older than 6 are missing some json properties (the same happened with Legacysnap)

**Comment by Savefade** [comment]
i finally figured out how to keep the client from logging out. i just needed to set a cookie with the name sessionid. if you want to add into your build paste this line in login     setcookie("sessionid", "banana", time() + ($cookieexpiresin * 30), "/");  after the password verify check

**Comment by upintheairsheep** [comment]
> i finally figured out how to keep the client from logging out. i just needed to set a cookie with the name sessionid. if you want to add into your build paste this line in login setcookie("sessionid", "banana", time() + ($cookieexpiresin * 30), "/"); after the password verify check

I'd suggest switching to Claude 3 Opus, heard it performs  in the ~86% range compared to ChatGPT w/ GPT4V and Google Bard Premium
